[package]
name = "chemef"
version = "0.1.0"
authors = ["kiwiyou <kiwiyou.dev@gmail.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]


[dependencies]
seed = "^0.6.0"
wasm-bindgen = "^0.2.50"


[dev-dependencies]
wasm-bindgen-test = "0.2.50"


[profile.release]
lto = true
opt-level = 'z'
